version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ltodo-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-todo_app}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ltodo-network

  backend:
    container_name: ltodo-backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-todo_app}
      # JWT_SECRET: your_jwt_secret
    depends_on:
      - postgres
    networks:
      - ltodo-network
  frontend:
    container_name: ltodo-frontend
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - ltodo-network

networks:
  ltodo-network:
    driver: bridge

volumes:
  postgres_data:
